config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :users, only: [:new, :create]
  resources :favorites, only: [:create, :destroy, :index]

  resources :gifs, only: [:index]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :categories, only: [:new, :create, :destroy, :index]
    resources :gifs, only: [:destroy, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :gifs, dependent: :destroy

  def gif_count
    gifs.count
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :gif

  def self.sort_by_category
    joins(gif: :category).order("name ASC")
  end
end

app/models/gif.rb
require 'net/http'
require 'json'

class Gif < ApplicationRecord
  validates :url, presence: true, uniqueness: true

  belongs_to :category
  has_many :favorites
  has_many :users, through: :favorites

  def self.retrieve_gif(category)
    key = ENV['giphy_key']
    url = "https://api.giphy.com/v1/gifs/random?api_key=#{key}&tag=#{category}&rating=G"
    resp = Net::HTTP.get_response(URI.parse(url))
    buffer = resp.body
    result = JSON.parse(buffer)
    if Gif.find_by(url: result["data"]["image_url"])
      byebug
      self.retrieve_gif(category)
    else
      result
    end
  end

  def self.sort_by_category
    joins(:category).order("categories.name")
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  has_secure_password

  has_many :favorites
  has_many :gifs, through: :favorites

  enum role: ["default", "admin"]

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  before_action :current_admin

  def current_admin
    render_404 unless admin?
  end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :downcase_params, only: :create

  def index
    @categories = Category.all
  end
#
  def new
    @category = Category.new
  end

  def create
    json_gif = Gif.retrieve_gif(params[:category][:name])
    @category = Category.find_by(name: params[:category][:name])
    if @category == nil
      @category = Category.create(category_params)
    end
    @category.gifs.create(url: json_gif["data"]["image_url"])
    redirect_to admin_gifs_path
  end

  def destroy
    @category = Category.find(params[:id])
    flash[:delete] = "#{@category.name.capitalize} has been deleted with all gifs."
    @category.destroy
    redirect_to admin_categories_path
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end

    def downcase_params
      category_params[:name].downcase!
    end
end

app/controllers/admin/gifs_controller.rb
class Admin::GifsController < Admin::BaseController

  def index
    @gifs = Gif.sort_by_category
  end

  def destroy
    @gif = Gif.find(params[:id])
    @gif.destroy
    flash[:delete] = "Gif Successfully deleted!"
    redirect_to admin_gifs_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :admin?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def admin?
    current_user && current_user.admin?
  end

  def render_404
    render file: "#{Rails.root}/public/404", layout: false, status: :not_found
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :logged_in?

  def index
    user = current_user
    @favorites = Favorite.where(user_id: user.id).sort_by_category
    if @favorites.empty?
      flash[:empty] = "You currently have no favorites"
      redirect_to gifs_path
    else
      render :index
    end
  end

  def create
    @favorite = Favorite.new(user_id: current_user.id, gif_id:params[:gif_id])
    if @favorite.save
      flash[:save] = "Your favorite has been saved"
    else
      flash[:error] = "Something went wrong, please try again"
    end
      direct_to_gifs
  end

  def destroy
    favorite = Favorite.find(params[:id])
    flash[:unfavorite] = "Successfully Unfavorited"
    favorite.destroy
    redirect_to favorites_path
  end

  private
    def logged_in?
      render_404 unless current_user
    end

    def direct_to_gifs
      if admin?
        redirect_to admin_gifs_path
      else
        redirect_to gifs_path
      end
    end
end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController
  def index
    @gifs = Gif.sort_by_category
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      redirect_to gifs_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:sessions][:username])
    if user && user.authenticate(params[:sessions][:password])
      session[:user_id] = user.id
      redirect_to favorites_path
    else
      flash[:failure] = "Incorrect Log In"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to favorites_path
    else
      render :new
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :password)
    end

    def logged_in?
      render_404 unless current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/index.html.erb
<h2>Existing Categories</h2>

<% @categories.each do |category| %>
  <div class="category">
    <h4><%= category.name.capitalize %> </h4>
    <p> Gif Total: <%= category.gif_count %> </p>
    <%= button_to "Delete", admin_category_path(category), method: "delete" %>
  </div>
<% end %>

app/views/admin/categories/new.html.erb
<h2>Generate Gif</h2>
<%= form_for [:admin, @category] do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Generate Gif"%>
<% end %>

app/views/admin/gifs/index.html.erb
<h2>Gifs</h2>

<% @gifs.each do |gif| %>
  <div class="images">
    <div class = "gif-title">
      <%= gif.category.name.capitalize %>
    </div>
    <img src="<%= gif.url %>"/>
    <%= button_to "Delete", admin_gif_path(gif), method: "delete" %>
    <% if gif.favorites.where(user_id: current_user.id).find_by(gif_id: gif.id) %>
      <%= button_to "Add to Favorites", favorites_path(gif_id: gif.id), disabled: true %>
    <% else %>
      <%= button_to "Add to Favorites", favorites_path(gif_id: gif.id), onclick: 'return disable(this)' %>
    <% end %>
  </div>
<% end %>

<script>
  function disable(element) {
    element.disabled = true;
    element.parentElement.submit();
  }
</script>

app/views/favorites/index.html.erb
<h3><%= current_user.username.capitalize %>'s  Favorites</h3>

<% @favorites.each do |favorite| %>
  <% gif = favorite.gif %>
  <div class="images">
    <div class = "gif-title">
      <%= gif.category.name.capitalize %>
    </div>
    <img src="<%= gif.url %>"/>
    <%= button_to "Unfavorite", favorite_path(favorite), method: "delete" %>
  </div>
<% end %>

app/views/gifs/index.html.erb
<h2>Gifs</h2>

<% @gifs.each do |gif| %>
  <div class="images">
    <div class = "gif-title">
      <%= gif.category.name.capitalize %>
    </div>
    <img src="<%= gif.url %>"/>
    <% if gif.favorites.where(user_id: current_user.id).find_by(gif_id: gif.id) %>
      <%= button_to "Add to Favorites", favorites_path(gif_id: gif.id), disabled: true %>
    <% else %>
      <%= button_to "Add to Favorites", favorites_path(gif_id: gif.id), onclick: 'return disable(this)' %>
    <% end %>
  </div>
<% end %>

<script>
  function disable(element) {
    element.disabled = true;
    element.parentElement.submit();
  }
</script>

app/views/home/index.html.erb
<h1> Welcome to Gif Generator! </h1>
<p>New User? <%=link_to "Create an Account", new_user_path %></p>
<p>Existing User? <%=link_to "Log In", login_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GifGenerator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if current_user %>
      <nav>
        <%=link_to "Favorites", favorites_path %>
        <% if admin? %>
          <%=link_to "Gifs", admin_gifs_path %>
          <%=link_to "Categories", admin_categories_path %>
          <%=link_to "New Gif", new_admin_category_path %>
        <% else %>
          <%=link_to "Gifs", gifs_path %>
        <% end %>
        <%=link_to "Log Out", logout_path, method: :delete %>
      </nav>
    <% end %>
    <% flash.each do |type, message| %>
      <%= content_tag :div, message, class: "alert alert#{type}" %>
      <% flash.discard(type) %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h3>Please enter the information below to create an account </h3>
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username%>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "Create Account"%>
<% end %>